### ISSUE TITLE
How to insert image inside menu items so that every menu item will have image and text. 

### ISSUE THREAD

**Issue by punithbm** [kazuhiro4949/PagingKit#105]
Hello, Is there any way to insert an image in the menu items? Please let me know if there are any ways to do this.

**Comment by kazuhiro4949** [comment]
You need to make a custom cell inheriting PagingMenuCell. 
This library behaves like UITableView, so It expects to get a object inheriting PagingMenuCll.

How to make a cell by yourself:
https://github.com/kazuhiro4949/PagingKit#3-create-menu-ui
