### ISSUE TITLE
Update Cocoapods with 1.11.2?

### ISSUE THREAD

**Issue by nathanwhy** [kazuhiro4949/PagingKit#111]
It seems you have fixed the lift cycle issue with #107 . Could you please update cocoapods with 1.11.2?

**Comment by nathanwhy** [comment]
Another question, I try to use your iOS sample(`IndicatorViewController`),  `scroll(to page: Int)` cannot work in `firstLoad`.

**Comment by kazuhiro4949** [comment]
This change has some issues yet. I will release it soon.

**Comment by kazuhiro4949** [comment]
> Another question, I try to use your iOS sample(IndicatorViewController), scroll(to page: Int) cannot work in firstLoad.

I'll check it.

**Comment by kazuhiro4949** [comment]
I updated it.
https://github.com/kazuhiro4949/PagingKit/releases/tag/1.12.0
