### ISSUE TITLE
Support for iOS 12.0

### ISSUE THREAD

**Issue by nimitjarvis** [kazuhiro4949/PagingKit#113]
Hello,

Can you please add support for iOS 12.0+?
I have been getting the following error in the sample project when I run in the devices with iOS 12.4.4 and 12.4.5. However, it's working fine for devices with iOS 13+. 

Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /PagingKit-master/iOS Sample/iOS Sample/SimpleViewController.swift, line 67

Hoping to hear from you soon.

Thanks a ton.

**Comment by kazuhiro4949** [comment]
@nimitjarvis 
PagingKit supports iOS 12, but the sample app doesn't support it, because of @IBSegueAction.

@IBSegueAction works only on iOS 13. 
It connects the menuViewController variable with PagingMenuViewController on Storyboard. 

I will fix the sample supporting iOS 12.

**Comment by kazuhiro4949** [comment]
I fixed it on the master branch.
