### ISSUE TITLE
v1.12.0: Appearing vc's viewWillAppear is called after scrolling has ended

### ISSUE THREAD

**Issue by ikesyo** [kazuhiro4949/PagingKit#116]
That seems odd behavior to me; appearing vc's viewWillAppear should be called on `ContentsAppearanceHandler`'s `beginDragging`, but not on `stopScrolling`.

**Comment by kazuhiro4949** [comment]
Thank you for your opinion :)

> That seems odd behavior

I guess you're right, but It is difficult to decide the appearing vc before stopped scrolling. 
Because a user can scroll continuously without stopping.

Please let me know if you have any good idea.
