### ISSUE TITLE
menuViewController.cellAlignment = .center

### ISSUE THREAD

**Issue by MasahiroToyooka** [kazuhiro4949/PagingKit#121]
素晴らしいプロジェクトの共有をありがとうございます！

質問なのですが、
overlayのところでdataSourceを２つに減らし、cellAlignmentをcenterにすると少しずれてしまいました。何か解決方法はありますでしょうか？
![ダウンロード](https://user-images.githubusercontent.com/38667604/82512620-94d41180-9b4b-11ea-9b12-30ecf6bf2866.gif)

**Comment by kazuhiro4949** [comment]
報告ありがとうございます。
確認してみます。

**Comment by kazuhiro4949** [comment]
@MasahiroToyooka  こちら直しましたので一度確認お願いしますmm
