### ISSUE TITLE
UITableViewAlertForLayoutOutsideViewHierarchy warning

### ISSUE THREAD

**Issue by MasahiroToyooka** [kazuhiro4949/PagingKit#125]
Message in debugger:
>[TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x7f8cd8862e00; frame = (0 0; 375 559); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x600003338ab0>; animations = { bounds.origin=<CABasicAnimation: 0x600003dcc5a0>; bounds.size=<CABasicAnimation: 0x600003dcc5c0>; position=<CABasicAnimation: 0x600003dcc640>; }; layer = <CALayer: 0x600003ddbba0>; contentOffset: {0, 0}; contentSize: {375, 924}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <iOS_Sample.ContentTableViewController: 0x7f8cd7e13990>>

Following the instructions and adding a symbolic breakpoint shows stops in:

first
<img width="1328" alt="スクリーンショット 2020-06-03 12 04 30" src="https://user-images.githubusercontent.com/38667604/83591578-3cf9c980-a593-11ea-8c2d-9a0efcca746e.png">
second
<img width="1365" alt="スクリーンショット 2020-06-03 12 04 43" src="https://user-images.githubusercontent.com/38667604/83591612-4a16b880-a593-11ea-94fc-d6e94d61b3e8.png">

This error could not be confirmed on the "simple"

**Comment by chienplee** [comment]
I also have this issue, how did you solve this?
