### ISSUE TITLE
Is it possible to incorporate into Table View Cell?

### ISSUE THREAD

**Issue by tsuyoshi777** [kazuhiro4949/PagingKit#126]
Hello,
I want to use PagingKit in a Table View Cell.
Is it possible to incorporate into Table View Cell?

**Comment by kazuhiro4949** [comment]
I'm sorry to reply late.
You can put PagingContentViewController.view and PagingMenuViewCnotrller.view on table view cell.

**Comment by aleks990822** [comment]
> Hello, I want to use PagingKit in a Table View Cell. Is it possible to incorporate into Table View Cell?

Hello, were you able to put in tableview cell?
if yes, please share the solution
