### ISSUE TITLE
Underline and Title are not vertically aligned

### ISSUE THREAD

**Issue by longunidev** [kazuhiro4949/PagingKit#130]
![Screenshot at Feb 24 10-37-24](https://user-images.githubusercontent.com/55679507/108944409-41b85d80-768d-11eb-9a83-2410e7a8d83a.png)

My problem is described like the illustration image. The title and underline are not aligned vertically
What is the problem and hints to fix it please. Thank you in advance

**Comment by kazuhiro4949** [comment]
@longunidev  I'm sorry for the late reply.  Could you show me the code snippet?

**Comment by finlayjn** [comment]
Just ran into the same issue. My code is very closely based on the Reloadable example, but I can send some if it helps. For me, the issue seems to arise from adding and removing view controllers from the data source. I implemented the following workarounds:

Reset the underline when updating the data source:
```swift
var dataSource = [(menu: String, content: UIViewController)]() {
        didSet {
            menuViewController?.reloadData()
            contentViewController?.reloadData()
            menuViewController?.focusView.subviews.forEach {$0.removeFromSuperview()}
            menuViewController?.registerFocusView(view: UnderlineFocusView())
        }
    }
```

Scrolling away before removing a page also seems to help:
```swift
let closingIndex = menuViewController?.currentFocusedIndex
// Scroll to next page to the left if closing the rightmost page
if closingIndex == dataSource.count - 1 && dataSource.count > 1 {
    menuViewController?.scroll(index: closingIndex! - 1, animated: true)
    contentViewController?.scroll(to: closingIndex! - 1, animated: true)
// Otherwise, scroll to next page to the right
} else if dataSource.count > 1 {
    menuViewController?.scroll(index: closingIndex! + 1, animated: true)
    contentViewController?.scroll(to: closingIndex! + 1, animated: true)
    menuViewController?.scroll(index: closingIndex!, animated: false)
    contentViewController?.scroll(to: closingIndex!, animated: false)
}
dataSource.remove(at: (closingIndex)!)
```

**Comment by kazuhiro4949** [comment]
@finlayjn Thanks. I'm going to try to reproduce the issue.

**Comment by kazuhiro4949** [comment]
@finlayjn I couldn't reproduce the issue with MenuReloadableViewController. Could you give me any additional information?

**Comment by finlayjn** [comment]
Sure. Like I said I think it's an issue with updating the data source. More specifically, it seems to occur when the data source is empty and an item is added. Here's the changes I made to reproduce the issue in the MenuReloadableViewController example in the sample project:

Change "menus" constant to a variable and leave it empty to begin.
```swift
var menus: [String] = []
```

Add this line to the reloadButtonDidTap action before updating dataSource.
```swift
self.menus.append("Menu")
```

Run the app and press the Reload button. The first menu item that appears will not be aligned with its underline.
![Simulator Screen Shot - iPhone 12 Pro - 2021-05-16 at 16 54 21](https://user-images.githubusercontent.com/52335224/118417096-73770a00-b667-11eb-8ccf-48d9fc6af17b.png)

**Comment by kazuhiro4949** [comment]
@finlayjn thanks for your support. I fixed the issue.
