### ISSUE TITLE
Switch page programmatically 

### ISSUE THREAD

**Issue by huy-lv** [kazuhiro4949/PagingKit#131]
Hi, how to switch to another page programmatically, i think the code should look like:
```
page.selectedIndex = 2
```

**Comment by kazuhiro4949** [comment]
@huy-lv You can use the following methods.
```
pagingMenuViewController.scroll(index: 2)
pagingContentViewController.scroll(to: 2, animated: true)
```

https://github.com/kazuhiro4949/PagingKit/blob/master/Sources/PagingMenuViewController.swift#L165
https://github.com/kazuhiro4949/PagingKit/blob/master/Sources/PagingContentViewController.swift#L204

and this
