### ISSUE TITLE
Without Storyboard

### ISSUE THREAD

**Issue by HermanKayy** [kazuhiro4949/PagingKit#132]
Hello can PagingKit be used without storyboard? I'm building everything programmatically currently.

**Comment by kazuhiro4949** [comment]
Yes it is.
PagingMenuViewController and PagingContentViewController are inherited from UIViewController.
So you can use them like UIViewController.
If you don't know how to add a child vc to a parent vc programmatically, please look up on the internet.

```swift
let contentViewController = PagingContentViewController()
let menuViewController = PagingMenuViewController()

addChild(contentViewController)
addChild(menuViewController)

// add view with Autolayout or Autoresizing
```
