### ISSUE TITLE
Can I preload all contentViewControllers?

### ISSUE THREAD

**Issue by richoh86** [kazuhiro4949/PagingKit#138]
Hi~!

I tried to preload all contentViewControllers before I tap the menus but It doesn't seem to work.
Is it impossible to load all contentViewControllers before tap or swipe the menu?

Thank you!

**Comment by kazuhiro4949** [comment]
@richoh86 I'm sorry for the late reply...

> Is it impossible to load all contentViewControllers before tap or swipe the menu?

It's not possible, because PagingKit saves an app's resource.
I recommend that you make view controllers as needed.
