### ISSUE TITLE
How to customise PagingMenuViewController overlay title  

### ISSUE THREAD

**Issue by arishanapalli** [kazuhiro4949/PagingKit#139]
How to change PagingMenuViewController title font colour for selected & unselected 
And also Overlay highlight gray color

**Comment by kazuhiro4949** [comment]
You can change the text color with the following properties.
 https://github.com/kazuhiro4949/PagingKit/blob/master/Sources/Menu%20Cells/Overlay/OverlayMenuCell.swift#L32L48
