### ISSUE TITLE
contentViewController 的 navigationController 是空的

### ISSUE THREAD

**Issue by 877209649** [kazuhiro4949/PagingKit#17]
self.navigationController 是空的，push不到子界面

**Comment by kazuhiro4949** [comment]
Thank you for your comment 😄 
I checked "contentViewController.navigationController" in [Sample Project](https://github.com/kazuhiro4949/PagingKit/tree/master/iOS%20Sample/iOS%20Sample). It didn't nil but UINavigationController object. 
Could you post the code?
(I'm sorry for writing in English.)

**Comment by kazuhiro4949** [comment]
I'm going to close this issue. If you have any trouble, feel free to reopen.
