### ISSUE TITLE
Lifecycle problem

### ISSUE THREAD

**Issue by Natai** [kazuhiro4949/PagingKit#19]
in your demo, just like your SimpleViewController, it's contentViewControllers call their viewDidLoad at the same time.

**Comment by kazuhiro4949** [comment]
Hi, @Natai .

When I modified the sample code for the layout of iPhoneX, I added some hot-fix.
https://github.com/kazuhiro4949/PagingKit/commit/6df1f47028aa783fd60215ca3082d6e7bb43d422#diff-4c11579eb36faa4b4db40f5defc65b16R31

It seems that "layoutIfNeeded" loads all the views. 
I'll fix the problem. Thanks you :)

**Comment by kazuhiro4949** [comment]
I fixed this issue on the following pull-request.
https://github.com/kazuhiro4949/PagingKit/pull/20

In addition, I solved the layout problem in another way.
https://github.com/kazuhiro4949/PagingKit/pull/20/commits/8b44c47211e40e2e2d79fceb9379f6c9ccf6a5c1
