### ISSUE TITLE
scroll useless

### ISSUE THREAD

**Issue by 877209649** [kazuhiro4949/PagingKit#22]
menuViewController?.scroll(index: 2)
contentViewController?.scroll(to: 2, animated: true)
The code useless

**Comment by 877209649** [comment]
PagingContentViewController.swift
code :192 line
`scroll(to: page, animated: animated) { [weak self] (finished) in
            guard let _self = self, finished else { return }
            _self.delegate?.contentViewController(viewController: _self, didFinishPagingAt: _self.leftSidePageIndex, animated: animated)
        }
`
execute twice  
first time  page correct 
second time page == 0

**Comment by 877209649** [comment]
contentViewController?.reloadData(with: page, completion: nil)
menuViewController?.reloadData(with: page, completionHandler: nil)
It is successful for this way 
thank

**Comment by kazuhiro4949** [comment]
Hi, @877209649

Which timing did you call the methods?
I couldn't confirm the calling ```PagingContentViewController.scroll(to:animated:)``` twice in the sample app.
https://github.com/kazuhiro4949/PagingKit/blob/master/iOS%20Sample/iOS%20Sample/SimpleViewController.swift#L107

**Comment by kazuhiro4949** [comment]
I'm going to close this issue. If you have any trouble, feel free to reopen.
