### ISSUE TITLE
Underline is not visible anymore, see example code for simple!

### ISSUE THREAD

**Issue by HomanF** [kazuhiro4949/PagingKit#30]

**Comment by kazuhiro4949** [comment]
I'm soooo sorry!

**Comment by HomanF** [comment]
No problem :) 

Also I have problem with the content inset to add padding from 1.2.0, it won't change the padding, any ideas why?

What I'm trying to do is when I have 3 menus/title I want it to be center but at the same time resize the underline, how could I manage that?

**Comment by kazuhiro4949** [comment]
I'll check the padding problem later.

You can change PagingMenuViewController.view.bounds.width on storyboard or view controller.  
It is one of the way to change the menu layout.

1. Set a constraint of x axis to PagingMenuViewController in Storyboard.
2. Set a constraint of the width to PagingMenuViewController in Storyboard. 
3. Add IBOutlet of width constraint to your ViewController.

http://www.iosinsight.com/access-storyboard-and-xib-constraints-in-code/

You can set any width according to the number of item.
Please try :)

**Comment by kazuhiro4949** [comment]
I released 1.2.1

https://github.com/kazuhiro4949/PagingKit/releases/tag/1.2.1

**Comment by HomanF** [comment]
Great thanks alot :) 

I noticed also for editing underline height in UnderlineFocusView class, your forgot to add the var to the private func setup.

Now its
attribute: .height, multiplier: 1, constant: 4))

It should be 
attribute: .height, multiplier: 1, constant: underlineHeight))


And how do I access this var from my vc to change it? 


Regards Homan

**Comment by kazuhiro4949** [comment]
I'd clean forgotten underlineHeight :p 
I'll fix it toooo.

**Comment by kazuhiro4949** [comment]
I released 1.2.2
https://github.com/kazuhiro4949/PagingKit/releases/tag/1.2.2

**Comment by kazuhiro4949** [comment]
> And how do I access this var from my vc to change it?

You can set a value to the property with v1.2.2.

```swift
let focusView = UnderlineFocusView()
focusView.underlineHeight = 10
menuViewController?.registerFocusView(view: focusView)
```

**Comment by HomanF** [comment]
great thanks alot :) but same goes for underlineColor! sorry

**Comment by HomanF** [comment]
Same goes for TitleLabelMenuViewCell

 ///  The text color when selecred
    public var focusColor = UIColor.pk.focusRed {
        didSet {
            titleLabel.textColor = focusColor
        }
    }

    /// The normal text color.
    public var normalColor = UIColor.black {
        didSet {
            titleLabel.textColor = normalColor
        }
    }

**Comment by kazuhiro4949** [comment]
Thanks a lot lol. 
I'll fix them later.

TitleLabelMenuViewCell is reused in PagingMenuView again and again. 
So I'll change the style properties to static.

**Comment by kazuhiro4949** [comment]
@HomanF 
I decided to add "didSet" as you mentioned. 
TitleLabelMenuViewCell's property assumes to be set on ```cellForItemAt```.

```swift
    func menuViewController(viewController: PagingMenuViewController, cellForItemAt index: Int) -> PagingMenuViewCell {
        let cell = viewController.dequeueReusableCell(withReuseIdentifier: "identifier", for: index)  as! TitleLabelMenuViewCell
        cell.focusColor = .blue
        cell.normalColor = .red
        cell.isSelected = (viewController.currentFocusedIndex == index)
        cell.titleLabel.text = dataSource[index].menu
        return cell
    }
```

**Comment by kazuhiro4949** [comment]
@HomanF 
I fixed the problems. 
Thank you for your contribution :)

**Comment by kazuhiro4949** [comment]
I added cellAlignment feature in 1.3.0. So you can cells in the center.
https://github.com/kazuhiro4949/PagingKit/releases/tag/1.3.0

> What I'm trying to do is when I have 3 menus/title I want it to be center but at the same time resize the underline to fit the text width, how could I manage that?
