### ISSUE TITLE
Xcode 9.2 new build system fails with “unable to build node” error

### ISSUE THREAD

**Issue by purplecofe** [kazuhiro4949/PagingKit#37]
can fix this problem?

**Comment by kazuhiro4949** [comment]
Thanks. I have never checked new build system in Xcode9. I'll do that.

**Comment by kazuhiro4949** [comment]
@purplecofe 
I fixed the issue in the above pull-request. Please check the v1.2.5.

**Comment by purplecofe** [comment]
Thanks
