### ISSUE TITLE
alignment property like UILabel.textAlignment

### ISSUE THREAD

**Issue by kazuhiro4949** [kazuhiro4949/PagingKit#40]
I want a convenience method to align cells when PagingMenuView.contentSize.width is shorter than PagingMenuView.bounds.width.

```swift
menuViewController.alignment = .center
// |     |menu1|menu2|menu3|      |
menuViewController.alignment = .right
// |           |menu1|menu2|menu3||
menuViewController.alignment = .left // default
// ||menu1|menu2|menu3|           |

```

**Comment by kazuhiro4949** [comment]
merged

**Comment by wousser** [comment]
I'd like to reopen this issue as alignment settings are not applied in viewDidLoad() method. Only after the view has been loaded alignment settings are applied.

To reproduce, open the iOS sample project, in AlignmentViewController.swift in viewDidLoad() change .left to .center. Run the app and the alignment is still left aligned.
