### ISSUE TITLE
FocusView will not work after MenuViewController reload

### ISSUE THREAD

**Issue by guloooo128** [kazuhiro4949/PagingKit#41]
After the first load is complete, the focusView will not work when I reload the MenuViewController and change the width of the MenuCell

**Comment by kazuhiro4949** [comment]
Hi, @guloooo128
Thanks you for your question :)

Could you check out this repository with download link and open the workspace?
https://github.com/kazuhiro4949/PagingKit/archive/master.zip

It may works fine. 
Follow the code in your project.

If you have some trouble to do that, show me the code :)

**Comment by PoissonBallon** [comment]
I have the same error here :/ 
Xcode 9.2 and iOS 11

**Comment by kazuhiro4949** [comment]
Hi, @PoissonBallon

Thank you for the advice.
I will check and fix the bug :(

**Comment by kazuhiro4949** [comment]
I confirmed the same error on a sample view controller. I'll inspect the cause.

**Comment by kazuhiro4949** [comment]
@guloooo128 @PoissonBallon 
I fixed the issue. Could you check the problematic code?
https://github.com/kazuhiro4949/PagingKit/releases/tag/1.4.0

**Comment by PoissonBallon** [comment]
Not fixing my issue in my case but I think it's a different case, 
when I `reloadData` my contentViewController focus on the first content, but menuViewController is still on the current menu :/

**Comment by kazuhiro4949** [comment]
@PoissonBallon 
If you want to reload data both contentViewController and menuViewController, you need to reload both. This library doesn't provide the feature to reload synchronously.

**Comment by notice** [comment]
Hi,@kazuhiro4949

I encounter a similar issue related to tab focus.

PagingKit1.5.1

the way to reproduce:

use TagViewController in the repository as sample.

Add viewWillAppear method.

```
override func viewWillAppear(_ animated: Bool) {
  super.viewWillAppear(animated)
  menuViewController?.reloadData()
  contentViewController?.reloadData()
}
```

1. Run the sample program.
2. And select "tag" in the main menu.
3. Select a last tab(may be around the last).
4. Tap "Present Modally".
5. Tap "Done".
6.  And then reload, Focusing of the last tab has gone.

The indexes are correct.

```
menuViewController.currentFocusedIndex
contentViewController.currentPageIndex
```

I think that the last tab data may be lack in visibleCells[].

**Comment by kazuhiro4949** [comment]
@notice
I fixed the bug referring to your advice. 
Thanks.

**Comment by notice** [comment]
@kazuhiro4949 
Not at all. I appreciate your swift response. PagingKit is great!
