### ISSUE TITLE
Ignore content insets when scrolling

### ISSUE THREAD

**Issue by jagaapple** [kazuhiro4949/PagingKit#47]
Hi! We can set content insets of PagingMenuViewController, but ignore them when scrolling.

```swift
menuViewController.contentInset = UIEdgeInsets(top: 0.0, left: 44.0, bottom: 0.0, right: 44.0)
```

![hoge](https://user-images.githubusercontent.com/20621562/37153388-ef0b7b94-231f-11e8-9077-f949634f07b4.gif)

I confirmed on iOS 11.2 and 10.3.
Thank you.

**Comment by kazuhiro4949** [comment]
@jagaapple Hi, @jagaapple. I'll fix the issue soon :)

**Comment by kazuhiro4949** [comment]
@francoisrouault I've merged https://github.com/kazuhiro4949/PagingKit/pull/64 and revert some commits to support jail-broken apps. Version 1.6.1 is fixed the issue.

https://github.com/kazuhiro4949/PagingKit/releases/tag/1.6.1

thanks.
