### ISSUE TITLE
Size of PagingMenuViewController incorrectly

### ISSUE THREAD

**Issue by wousser** [kazuhiro4949/PagingKit#49]
PagingMenuViewController container does not respect AutoLayout size information.

Steps to reproduce in iOS Sample
- PagingMenuViewController container is aligned to leading and trailing edge.
- Set Storyboard device to iPhone SE. Container width is now 320.
- Run on iPhone 6 or 8, the Container width should be 375 but is still 320. Or should be 320 and is 270.
![pagingmenucontroller bug](https://user-images.githubusercontent.com/1159336/37398015-1735c6a0-27b8-11e8-87d9-0f362e7bfc1d.png)

Also please look at this other alignment issue: #40 

Thanks!

**Comment by kazuhiro4949** [comment]
Hi, @wousser. 
Thank you  writing issue in detail. 
I create a new branch. It may fix the bug. Could you check it?
 If you have another trouble, feel free to contact me.

PagingMenuViewController container's width equal to UIScrollView.contentSize.width. 
It is correct that the container's width is shorter than the parent view's width.

**Comment by wousser** [comment]
Yes, both issue #40 and #49 are fixed in branch "feature/fixAlignment".

Thank you very much, and thanks for writing this library!

**Comment by kazuhiro4949** [comment]
Your welcome 😉 I released v1.5.1
https://github.com/kazuhiro4949/PagingKit/releases
