### ISSUE TITLE
Can I use PagingKit without Storyboard?

### ISSUE THREAD

**Issue by wahello** [kazuhiro4949/PagingKit#62]
Can I use PagingKit without Storyboard? Is there example without storyboard? @kazuhiro4949

**Comment by kazuhiro4949** [comment]
Hi, @keyeMyria.

> Can I use PagingKit without Storyboard?
Yes, you do. Each class in PagingKit is kind of UIViewController or UIView.
So you can initialize them as you initialize UIViewController or UIView.

> Is there example without storyboard?
I'm sorry that my document doesn't have the example. 
I will write it later.

**Comment by kazuhiro4949** [comment]
Hi, @keyeMyria 

I added the sample view controller.
see https://github.com/kazuhiro4949/PagingKit/blob/master/Documentation/Tips.md#initializing-without-storyboard.
