### ISSUE TITLE
How to trigger viewController lifecycle when I scrolling.

### ISSUE THREAD

**Issue by JiaWeiXie** [kazuhiro4949/PagingKit#63]

**Comment by JiaWeiXie** [comment]
Hi @kazuhiro4949 .

I'm sorry, I didn't describe the problem in detail.
View controllers in PagingContentViewController is not a problem, but I want to run viewDidAppear() when user swiped to next view.

**Comment by kazuhiro4949** [comment]
Hi @JiaWeiXie 

When You want to call viewDidAppear() explicitly, you need to call [beginAppearanceTransition(_:animated:)(https://developer.apple.com/documentation/uikit/uiviewcontroller/1621387-beginappearancetransition) and [endAppearanceTransition()](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621503-endappearancetransition).

If you wanna hook paging event (for example sending event log), I recommend you putting yoru implementation on each the delegate of PagingContentViewController.
https://github.com/kazuhiro4949/PagingKit/blob/master/PagingKit/PagingContentViewController.swift#L28

**Comment by JiaWeiXie** [comment]
Hi @kazuhiro4949 

I've already dealt with it in other ways, but I am very grateful for your suggestion.
