### ISSUE TITLE
Xcode 10, Swift 4.2 error

### ISSUE THREAD

**Issue by ETHANAIR** [kazuhiro4949/PagingKit#65]
<img width="356" alt="2018-09-19 4 34 52" src="https://user-images.githubusercontent.com/8438205/45741360-f5e66c00-bc29-11e8-888c-8513c211bf0d.png">

**Comment by katerynasytnykiOS** [comment]
+1 !! Makes it unusable otherwise..

**Comment by kazuhiro4949** [comment]
@ETHANAIR Thanks for your reporting. I'll fix it on Xcode 10.

**Comment by kazuhiro4949** [comment]
PagingKit is support only swift 4.2 in the next version (v1.6.4)

**Comment by kazuhiro4949** [comment]
I released v1.6.4 supporting Xcode 10
https://github.com/kazuhiro4949/PagingKit/releases/tag/1.6.0
