### ISSUE TITLE
RxSwift supported wanted

### ISSUE THREAD

**Issue by lm2343635** [kazuhiro4949/PagingKit#66]
It is more convenient to bind data to PagingKit using FRP libraries just like RxDataSources.

**Comment by kazuhiro4949** [comment]
I have already made RxPagingKit.

https://github.com/kazuhiro4949/RxPagingKit

**Comment by lm2343635** [comment]
Why not add RxPagingKit as a sub podsepc in PagingKit like this:
```
pod 'PagingKit/Rx'
```
