### ISSUE TITLE
[Help] Need to create custom highlighted(bubble) indicator

### ISSUE THREAD

**Issue by Sergozh** [kazuhiro4949/PagingKit#75]
Hey, @kazuhiro4949 ! I love your framework so much.

Could you help me and give an advice is it possible to implement custom indicator view like on images below? Thank you.

![img_4797](https://user-images.githubusercontent.com/1511211/47255140-f8c8bc80-d474-11e8-993e-ad7116bf4855.jpg)
![img_4796](https://user-images.githubusercontent.com/1511211/47255142-fc5c4380-d474-11e8-94c1-2cc8471146d6.jpg)

**Comment by kazuhiro4949** [comment]
@Sergozh  I added a new feature to support this UI.  If you have any trouble, feel free to reopen.

**Comment by kazuhiro4949** [comment]
See https://github.com/kazuhiro4949/PagingKit/blob/master/Documentation/Tips.md#animating-alongside-pagingmenufocusview or OverlayViewController in the current master branch
