### ISSUE TITLE
Selected Tab Color

### ISSUE THREAD

**Issue by inPhilly** [kazuhiro4949/PagingKit#8]
Great control! For the tab style, is there a way to change the color of a tab once it becomes selected? This feature would be amazing.

**Comment by kazuhiro4949** [comment]
@inPhilly 
Thank you for your suggestion :)

It is easy to change tab styles when a tab  is selected. PageMenuViewController provides events to check changing tab state. I added how to check the events to "iOS Sample". check the sample code.

https://github.com/kazuhiro4949/PagingKit/commit/760fb4495f3ab6ea858aabccf5a3f7c599bc981a

In the delegate methods, you can change the color of a tab intermittently or continuously.

![sample_movie](https://user-images.githubusercontent.com/18320004/31849218-f5a634de-b679-11e7-98bb-035ce4316b29.gif)

![sample_movie_2](https://user-images.githubusercontent.com/18320004/31849219-f657db12-b679-11e7-99fb-4a8baac861a6.gif)

**Comment by kazuhiro4949** [comment]
This issue should be resolved. I will close it. If you have another trouble, feel free to reopen.
