### ISSUE TITLE
Button in the MenuView.

### ISSUE THREAD

**Issue by lm2343635** [kazuhiro4949/PagingKit#80]
Button in the menu view cannot be clicked because of the PagingFocusView. 

![image](https://user-images.githubusercontent.com/9463655/48895803-4cba2d00-ee89-11e8-9c9b-488ee4c4067c.png)

**Comment by kazuhiro4949** [comment]
Hi, @lm2343635
Assign false to isUserInteractionEnabled of PagingMenuFocusView. 

```
pagingMenuViewController.focusView.isUserInteractionEnabled = false
```

**Comment by lm2343635** [comment]
@kazuhiro4949 
It works! 
Thank you very much!
