### ISSUE TITLE
Crash when numberOfItemsForMenuViewController return 0

### ISSUE THREAD

**Issue by RaziPour1993** [kazuhiro4949/PagingKit#85]
Crash when numberOfItemsForMenuViewController return 0

![screen shot 1397-10-26 at 01 47 59](https://user-images.githubusercontent.com/16708111/51213799-2d8fc700-1931-11e9-9868-9ebe62813da8.png)

![screen shot 1397-10-26 at 01 48 30](https://user-images.githubusercontent.com/16708111/51213812-354f6b80-1931-11e9-977c-4fb3fe435827.png)

**Comment by kazuhiro4949** [comment]
@RaziPour1993 Thanks for your reporting. What is the version of PagingKit?

**Comment by kazuhiro4949** [comment]
I'll close this issue. If you still have the same crash, reopen this.
