### ISSUE TITLE
Pod update can't find version 1.10.0

### ISSUE THREAD

**Issue by jkpang** [kazuhiro4949/PagingKit#89]
1. `pod setup`
2. `pod search PagingKit`
![image](https://user-images.githubusercontent.com/17583451/55207520-79a29600-5215-11e9-9ff1-482f2ef9c5ca.png)

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by kazuhiro4949** [comment]
@jkpang Thanks for reporting. I updated Cocoapods repository too.
