### ISSUE TITLE
Populate content with different controller

### ISSUE THREAD

**Issue by snc001** [kazuhiro4949/PagingKit#90]
I was wondering if there was a way to populate the content with collection view??

I am getting issue where when I pass in another controller like this:

`var dataSource: [(menu: String, content: UIViewController)] = [
        (menu: "menu1", content: viewController(.blue)),
        (menu: "menu2", content: SecondViewController())
  ]
`

my SecondViewController only holds an imageView:

`class SecondViewController: UIViewController {

    @IBOutlet weak var dankImage: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        let imageToSet = UIImage(named: "Dank")
        dankImage.image = imageToSet!
    }
}`

When i swipe it always show that it cannot unwrap and returns "nil" - but if i remove setting the image to image view so its blank. This runs fine.

How does this work under the hood when populating view?

**Comment by kazuhiro4949** [comment]
@snc001 You mean SecondViewController doesn't show image? Does it call viewDidLoad()?

**Comment by snc001** [comment]
> You mean SecondViewController doesn't show image? Does it call viewDidLoad()?

Yes thats right and yes it does call "viewDidLoad()" - I can confirm that if I don't pass the view controller in as -

`    var dataSource: [(menu: String, content: UIViewController)] = [
        (menu: "menu1", content: viewController(.red)),
        (menu: "menu2", content: SecondViewController())
    ]`

My view controller works and the image is inflated fine with this - 

```
@IBOutlet weak var dankImage: UIImageView!

override func viewDidLoad() {
    super.viewDidLoad()

    let imageToSet = UIImage(named: "Dank")
    dankImage.image = imageToSet!
}
```

**Comment by kazuhiro4949** [comment]
Did You make the view controller on Storyboard? It looks have dankimage as IBOutlet.
If that, you needs to instantiate the vc via UIStoryboard.

**Comment by snc001** [comment]
> Did You make the view controller on Storyboard? It looks have dankimage as IBOutlet.
> If that, you needs to instantiate the vc via UIStoryboard.

Yes I did and that did the trick - thank you 😊
