### ISSUE TITLE
Parallax Header View Pager

### ISSUE THREAD

**Issue by nikolaveljic64** [kazuhiro4949/PagingKit#91]
![demo](https://user-images.githubusercontent.com/18101315/57542118-0b430e80-7351-11e9-9956-7bc221c44b49.gif)

How to implement this? Can this library do this? @kazuhiro4949

**Comment by kazuhiro4949** [comment]
@nikolaveljic64 This library doesn't support Parallax Header View. You can make only the bottom area with this library.
