### ISSUE TITLE
Option to disable preloading the next viewController?

### ISSUE THREAD

**Issue by hithakshi** [kazuhiro4949/PagingKit#95]
I have 3 viewControllers for paging. Everything is perfect except one.
**viewDidAppear()** of second viewController called when first viewController is loaded. 
Problem is we are presenting a viewController (basically a coach mark) when second view controller is loaded. Hence when first view controller appears, second viewController's presenting viewController (i.e coach mark) is shown. 

I have checked internal code of PagingKit. It has something called "**isEnabledPreloadContent**" property and '**preloadContentIfNeeded**' method which is not used anywhere. I believe if isEnabledPreloadContent is set to false, it should not load viewControllers which are yet to present/load. 

As a workaround, I am using **"menuViewController(viewController: PagingMenuViewController, didSelect page: Int, previousPage: Int) "** method to decide whether to present viewController or not. But this is not satisfying!!

**Comment by kazuhiro4949** [comment]
@hithakshi  
You can use the delegate to catch the event.

```swift
func contentViewController(viewController: PagingContentViewController, didFinishPagingAt index: Int, animated: Bool)
```

https://github.com/kazuhiro4949/PagingKit/blob/master/PagingKit/PagingContentViewController.swift#L75

PagingContentViewController calls it when the paging is finished.

 In addition, I'll add the feature to the next version. Please wait a while.

**Comment by hithakshi** [comment]
Yeah. I am currently using that. 
Thank you :)

**Comment by kazuhiro4949** [comment]
I'm glad that you could handle that problem :)
